[package]
name = "Gremlincli"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
console = "0.15.7"
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
colored = "2.1.0"
lazy_static = "1.4.0"
thiserror = "1.0"
chrono = "0.4.34"
